import { createFileRoute, Link } from "@tanstack/react-router";
import { Play, Headphones } from "lucide-react";
import { SiteLayout, SectionLabel } from "@/components/site/SiteLayout";
import { audios } from "@/lib/mock-data";
import { useT, useLang } from "@/lib/i18n";
import { audioThumbs, str } from "@/lib/thumbs";
import { buildStaticHead } from "@/lib/seo";

export const Route = createFileRoute("/music")({
  head: () =>
    buildStaticHead({
      path: "/music",
      title: "Music · 音乐 — AI商业宇宙 · AI Business Universe",
      description:
        "AI 原生环境音乐、写作与深度阅读音场 · AI-native ambient music and soundscapes for writing and deep reading.",
    }),
  component: MusicPage,
});

const chip = {
  lime: "bg-lime text-foreground",
  violet: "bg-violet text-white",
  signal: "bg-signal text-foreground",
  alert: "bg-alert text-white",
} as const;

function MusicPage() {
  const t = useT();
  const { lang } = useLang();
  const list = audios.filter((a) => a.kind === "music");
  return (
    <SiteLayout>
      <section className="border-b border-border bg-signal/10">
        <div className="mx-auto max-w-[1400px] px-6 py-14 lg:px-10 lg:py-20">
          <div className="flex items-center gap-3 text-[11px] font-semibold uppercase tracking-[0.24em] text-muted-foreground">
            <span className="rounded-full bg-signal px-3 py-1 text-foreground">Channel · Music</span>
            <span className="h-px flex-1 bg-border" />
            <span>{lang === "cn" ? "AI 原生音乐 · 环境音场" : "AI-native music · ambient soundscapes"}</span>
          </div>
          <h1 className="mt-6 font-display text-5xl leading-[0.95] text-foreground lg:text-7xl">
            {lang === "cn" ? "音乐" : "Music"} <span className="text-signal">/ Sound</span>
          </h1>
          <p className="mt-6 max-w-2xl text-lg text-foreground/75">
            {lang === "cn"
              ? "由多模态模型生成的环境音场,写作、深度阅读与远距离思考的背景音。"
              : "Ambient fields generated by multimodal models — for writing, deep reading and long-form thinking."}
          </p>
        </div>
      </section>

      <section className="mx-auto max-w-[1400px] px-6 py-16 lg:px-10 lg:py-24">
        <SectionLabel index="M · 01" label={lang === "cn" ? "AI 原生音乐" : "AI Native Music"} en="AI Native Music" color="signal" />
        <div className="mt-8 grid gap-6 md:grid-cols-2">
          {list.map((a) => (
            <Link
              key={a.id}
              to="/music/$slug"
              params={{ slug: a.slug }}
              className="group flex overflow-hidden rounded-lg border border-border bg-card transition-shadow hover:shadow-[0_20px_60px_-30px_rgba(0,0,0,0.35)]"
            >
              <div className="relative w-40 shrink-0 sm:w-56">
                <img src={audioThumbs[a.thumb]} alt={str(a.title)} loading="lazy" width={640} height={640} className="h-full w-full object-cover" />
                <span className="absolute bottom-3 left-3 flex h-10 w-10 items-center justify-center rounded-full bg-background text-foreground shadow">
                  <Play className="h-4 w-4 fill-current" />
                </span>
              </div>
              <div className="flex flex-1 flex-col gap-3 p-5">
                <div className="flex items-center justify-between text-[11px] font-semibold uppercase tracking-[0.2em]">
                  <span className={`rounded-full px-2.5 py-1 ${chip[a.color]}`}>{t(a.category)}</span>
                  <span className="flex items-center gap-1 text-muted-foreground">
                    <Headphones className="h-3 w-3" />
                    {a.duration}
                  </span>
                </div>
                <h3 className="font-display text-xl leading-snug group-hover:text-violet">{t(a.title)}</h3>
                <p className="text-sm text-muted-foreground">{t(a.excerpt)}</p>
              </div>
            </Link>
          ))}
        </div>
      </section>
    </SiteLayout>
  );
}
