/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as PlaybooksRouteImport } from './routes/playbooks'
import { Route as MusicRouteImport } from './routes/music'
import { Route as KeyPlayersRouteImport } from './routes/key-players'
import { Route as ConsultingRouteImport } from './routes/consulting'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AiNowRouteImport } from './routes/ai-now'
import { Route as AgenticAiRouteImport } from './routes/agentic-ai'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideoSlugRouteImport } from './routes/video.$slug'
import { Route as ReportsSlugRouteImport } from './routes/reports.$slug'
import { Route as PodcastSlugRouteImport } from './routes/podcast.$slug'
import { Route as MusicSlugRouteImport } from './routes/music.$slug'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as ApiAgentRouteImport } from './routes/api/agent'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksRoute = PlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyPlayersRoute = KeyPlayersRouteImport.update({
  id: '/key-players',
  path: '/key-players',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultingRoute = ConsultingRouteImport.update({
  id: '/consulting',
  path: '/consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AiNowRoute = AiNowRouteImport.update({
  id: '/ai-now',
  path: '/ai-now',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenticAiRoute = AgenticAiRouteImport.update({
  id: '/agentic-ai',
  path: '/agentic-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoSlugRoute = VideoSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VideoRoute,
} as any)
const ReportsSlugRoute = ReportsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ReportsRoute,
} as any)
const PodcastSlugRoute = PodcastSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PodcastRoute,
} as any)
const MusicSlugRoute = MusicSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MusicRoute,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agent': typeof AgentRoute
  '/agentic-ai': typeof AgenticAiRoute
  '/ai-now': typeof AiNowRoute
  '/analysis': typeof AnalysisRoute
  '/consulting': typeof ConsultingRoute
  '/key-players': typeof KeyPlayersRoute
  '/music': typeof MusicRouteWithChildren
  '/playbooks': typeof PlaybooksRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trends': typeof TrendsRoute
  '/video': typeof VideoRouteWithChildren
  '/api/agent': typeof ApiAgentRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/music/$slug': typeof MusicSlugRoute
  '/podcast/$slug': typeof PodcastSlugRoute
  '/reports/$slug': typeof ReportsSlugRoute
  '/video/$slug': typeof VideoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agent': typeof AgentRoute
  '/agentic-ai': typeof AgenticAiRoute
  '/ai-now': typeof AiNowRoute
  '/analysis': typeof AnalysisRoute
  '/consulting': typeof ConsultingRoute
  '/key-players': typeof KeyPlayersRoute
  '/music': typeof MusicRouteWithChildren
  '/playbooks': typeof PlaybooksRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trends': typeof TrendsRoute
  '/video': typeof VideoRouteWithChildren
  '/api/agent': typeof ApiAgentRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/music/$slug': typeof MusicSlugRoute
  '/podcast/$slug': typeof PodcastSlugRoute
  '/reports/$slug': typeof ReportsSlugRoute
  '/video/$slug': typeof VideoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agent': typeof AgentRoute
  '/agentic-ai': typeof AgenticAiRoute
  '/ai-now': typeof AiNowRoute
  '/analysis': typeof AnalysisRoute
  '/consulting': typeof ConsultingRoute
  '/key-players': typeof KeyPlayersRoute
  '/music': typeof MusicRouteWithChildren
  '/playbooks': typeof PlaybooksRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trends': typeof TrendsRoute
  '/video': typeof VideoRouteWithChildren
  '/api/agent': typeof ApiAgentRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/music/$slug': typeof MusicSlugRoute
  '/podcast/$slug': typeof PodcastSlugRoute
  '/reports/$slug': typeof ReportsSlugRoute
  '/video/$slug': typeof VideoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agent'
    | '/agentic-ai'
    | '/ai-now'
    | '/analysis'
    | '/consulting'
    | '/key-players'
    | '/music'
    | '/playbooks'
    | '/podcast'
    | '/reports'
    | '/sitemap.xml'
    | '/trends'
    | '/video'
    | '/api/agent'
    | '/article/$slug'
    | '/music/$slug'
    | '/podcast/$slug'
    | '/reports/$slug'
    | '/video/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agent'
    | '/agentic-ai'
    | '/ai-now'
    | '/analysis'
    | '/consulting'
    | '/key-players'
    | '/music'
    | '/playbooks'
    | '/podcast'
    | '/reports'
    | '/sitemap.xml'
    | '/trends'
    | '/video'
    | '/api/agent'
    | '/article/$slug'
    | '/music/$slug'
    | '/podcast/$slug'
    | '/reports/$slug'
    | '/video/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agent'
    | '/agentic-ai'
    | '/ai-now'
    | '/analysis'
    | '/consulting'
    | '/key-players'
    | '/music'
    | '/playbooks'
    | '/podcast'
    | '/reports'
    | '/sitemap.xml'
    | '/trends'
    | '/video'
    | '/api/agent'
    | '/article/$slug'
    | '/music/$slug'
    | '/podcast/$slug'
    | '/reports/$slug'
    | '/video/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgentRoute: typeof AgentRoute
  AgenticAiRoute: typeof AgenticAiRoute
  AiNowRoute: typeof AiNowRoute
  AnalysisRoute: typeof AnalysisRoute
  ConsultingRoute: typeof ConsultingRoute
  KeyPlayersRoute: typeof KeyPlayersRoute
  MusicRoute: typeof MusicRouteWithChildren
  PlaybooksRoute: typeof PlaybooksRoute
  PodcastRoute: typeof PodcastRouteWithChildren
  ReportsRoute: typeof ReportsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrendsRoute: typeof TrendsRoute
  VideoRoute: typeof VideoRouteWithChildren
  ApiAgentRoute: typeof ApiAgentRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks': {
      id: '/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof PlaybooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/key-players': {
      id: '/key-players'
      path: '/key-players'
      fullPath: '/key-players'
      preLoaderRoute: typeof KeyPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulting': {
      id: '/consulting'
      path: '/consulting'
      fullPath: '/consulting'
      preLoaderRoute: typeof ConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-now': {
      id: '/ai-now'
      path: '/ai-now'
      fullPath: '/ai-now'
      preLoaderRoute: typeof AiNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentic-ai': {
      id: '/agentic-ai'
      path: '/agentic-ai'
      fullPath: '/agentic-ai'
      preLoaderRoute: typeof AgenticAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$slug': {
      id: '/video/$slug'
      path: '/$slug'
      fullPath: '/video/$slug'
      preLoaderRoute: typeof VideoSlugRouteImport
      parentRoute: typeof VideoRoute
    }
    '/reports/$slug': {
      id: '/reports/$slug'
      path: '/$slug'
      fullPath: '/reports/$slug'
      preLoaderRoute: typeof ReportsSlugRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/podcast/$slug': {
      id: '/podcast/$slug'
      path: '/$slug'
      fullPath: '/podcast/$slug'
      preLoaderRoute: typeof PodcastSlugRouteImport
      parentRoute: typeof PodcastRoute
    }
    '/music/$slug': {
      id: '/music/$slug'
      path: '/$slug'
      fullPath: '/music/$slug'
      preLoaderRoute: typeof MusicSlugRouteImport
      parentRoute: typeof MusicRoute
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MusicRouteChildren {
  MusicSlugRoute: typeof MusicSlugRoute
}

const MusicRouteChildren: MusicRouteChildren = {
  MusicSlugRoute: MusicSlugRoute,
}

const MusicRouteWithChildren = MusicRoute._addFileChildren(MusicRouteChildren)

interface PodcastRouteChildren {
  PodcastSlugRoute: typeof PodcastSlugRoute
}

const PodcastRouteChildren: PodcastRouteChildren = {
  PodcastSlugRoute: PodcastSlugRoute,
}

const PodcastRouteWithChildren =
  PodcastRoute._addFileChildren(PodcastRouteChildren)

interface ReportsRouteChildren {
  ReportsSlugRoute: typeof ReportsSlugRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsSlugRoute: ReportsSlugRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface VideoRouteChildren {
  VideoSlugRoute: typeof VideoSlugRoute
}

const VideoRouteChildren: VideoRouteChildren = {
  VideoSlugRoute: VideoSlugRoute,
}

const VideoRouteWithChildren = VideoRoute._addFileChildren(VideoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgentRoute: AgentRoute,
  AgenticAiRoute: AgenticAiRoute,
  AiNowRoute: AiNowRoute,
  AnalysisRoute: AnalysisRoute,
  ConsultingRoute: ConsultingRoute,
  KeyPlayersRoute: KeyPlayersRoute,
  MusicRoute: MusicRouteWithChildren,
  PlaybooksRoute: PlaybooksRoute,
  PodcastRoute: PodcastRouteWithChildren,
  ReportsRoute: ReportsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrendsRoute: TrendsRoute,
  VideoRoute: VideoRouteWithChildren,
  ApiAgentRoute: ApiAgentRoute,
  ArticleSlugRoute: ArticleSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
